Repository iterative/dvclive, pull requests merged in 2021-07, with the labels that each got.

#69 Save checkpoint for Keras
  dvclive/keras.py
Labels: discussion, enhancement

#35 keras: add test
  tests/conftest.py
  tests/test_keras.py
Labels: enhancement

#74 init: throw on dvc/dvclive config mismatch
  dvclive/__init__.py
  dvclive/error.py
  dvclive/metrics.py
  tests/test_main.py
Labels: enhancement

#126 build: tests: make tests run verbose
  .github/workflows/tests.yaml
Labels: maintenance, testing
