Repository iterative/dvclive, pull requests merged in 2022-09, with the labels that each got.

#285 data: Don't use `with_suffix` in `output_path`.
  src/dvclive/data/plot.py
  src/dvclive/data/scalar.py
  tests/test_data/test_scalar.py
Labels: bugfix

#303 gha: pin 3.10 to 3.10.6
  .github/workflows/tests.yml
Labels: maintenance

#304 pyproject: fix coverage config
  pyproject.toml
Labels: maintenance

#302 keras: add ability to pass live into callback
  src/dvclive/keras.py
  tests/test_keras.py
Labels: enhancement, A: frameworks

#308 bump mypy to 0.981, enable recursive type aliases
  .github/workflows/tests.yml
  pyproject.toml
  setup.cfg
  src/dvclive/keras.py
  src/dvclive/live.py
Labels: maintenance
